######################## default configuration ####################
baseURL = "/"
title = "Climate Crew | Mission to Planet Earth"
theme = "climate-crew"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = ['fr'] # desable language from here

disableKinds = ["taxonomy", "term"]


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/climate-crew-logo.png"
# Meta data
description = "This project is aimed at providing a digital historical perspective on primitive as well as scientific research on greenhouse and glaciation period. These two aspects of our climate can be investigated separately but works of naturalists, geologists, physicists and chemists have made it easier to understand them jointly."
author = "Achintya Jha"
# contact info
address = "Ahlcon International School, New Delhi, India"
mobile = "(Achintya add a number here)"
email = "achintyakjha@gmail.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = false
# preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false

# google map
[params.map]
enable = false

# cookies
[params.cookies]
enable = false
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 an initiative by students of Ahlcon International School"



################### English navigation ####################
  
[[Languages.en.menu.main]]
name = "blog"
url = "blog"
weight = 2

[[Languages.en.menu.main]]
name = "satellites"
url = "satellites"
weight = 3
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "satellites"
  name = "Inception"
  url = "satellites/the-inception"

  [[Languages.en.menu.main]]
  parent = "satellites"
  name = "AQUA"
  url = "satellites/aqua"

  [[Languages.en.menu.main]]
  parent = "satellites"
  name = "CLOUDSAT"
  url = "satellites/cloudsat"

  [[Languages.en.menu.main]]
  parent = "satellites"
  name = "DSCOVR"
  url = "satellites/dscovr"

[[Languages.en.menu.main]]
name = "The story of climate"
url = "blog"
weight = 4
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "The story of climate"
  name = "Primitive Interpretation"
  url = "blog/primitive-interpretation"

  [[Languages.en.menu.main]]
  parent = "The story of climate"
  name = "Greenhouse to Glacials"
  url = "blog/greenhouse-to-glacials"

[[Languages.en.menu.main]]
name = "Sources"
url = "sources"
weight = 5